### ISSUE TITLE
Some questions about presicion recall curves

### ISSUE THREAD

**Issue by AgentLjc** [ma-compbio/LDGM#1]
Thanks for your work,I'm very interest in your work 'LDGM', but i have some questions about your **PR curves** in your paper.
could you please provide your code for plot these PR curves? or describe your curves simply? what does each point in your curves mean?I'm confused!
I will be appreciated if you reply.

**Comment by Tian-Dechao** [comment]
Hey AgentLjc

Thank you for your interest in our work. In short, each point in a PR curve
is (average of recall, average of precision) over k replicated run of LDGM
with the same tuning parameter lambda. The motivation is that, given a
fixed tuning parameter lambda, say 0.1, each run of LDGM will give an
estimate of the unknown differential network with some uncertainties. So we
rerun LDGM k times and take the average of the resulting k precisions as
the precision of LDGM with lambda at 0.1. Similarly for recall of LDGM with
lambda at 0.1, precision and recall of LDGM with other lambdas, precision
and recall of the other benchmark models with varying tuning parameters.

Pseudo for LDGM with a given tuning parameter lambda, say 0.1.

   1. Repeat LDGM k times.
      1. for each run, calculate precision, recall
   2. Take the average of k precision as the precision of LDGM with lambda
   at 0.1. Take the average of k recall as the recall of LDGM with lambda at
   0.1


The Python code for the step 2 and final touch (using interpolation) is
attached.

Thank you again for your interests in our work. Let us know if you have
other questions.


Best
Dechao

**Comment by AgentLjc** [comment]
Thanks for your reply!
So I think there shoule be 30 points(30 lambda) in each PR curve according your supplementary text. Am i right?
How do i choose the best lambda if I want to use your method on real data sets?Or using 30 lambda, will it consume too much time?Or,how did you choose lambda on gene expression data from Luminal A and Basal-like subtypes.

**Comment by Tian-Dechao** [comment]
1. Yes. You are right.
2.  a) Regarding choosing the best lambda, our paper did not directly
address this problem. There is no one size fits all solution. Some papers
use 5-fold cross-validation to choose the best lambda. We did not employ
similar approaches in choosing the best lambda in real data analysis. One
of the motivations is that it requires both technical insights (like
cross-validation) and domain expertise (like knowledge and insight on
breast cancer).
    b) The speed of our model is decent. Improving the speed is not on our
to-do list in preparing the paper. Our model is written in Matlab. If you
want to try R code, you can try DiffGraph package in the paper "DiffGraph:
an R package for identifying gene network rewiring using differential
graphical models (
https://academic.oup.com/bioinformatics/article/34/9/1571/4772685
<https://mailtrack.io/trace/link/71271f9b0f2d7e1c4b2cb26e58dac8d393bf551a?url=https%3A%2F%2Facademic.oup.com%2Fbioinformatics%2Farticle%2F34%2F9%2F1571%2F4772685&userId=3509454&signature=ae80a8619c51dad4>)"
Our model is one of the four models in the package.
    c) In the real data analysis and other sections, our key message is
that our model consistently outperforms other models when the underlying
"true" differential networks have a varying density (total edges/total
possible edges). The application to breast cancer subtypes also tried a few
lambdas to reconstruct differential networks with increasing density (or
increasing edge numbers, Fig 5A-B). The differential network plotted in Fig
5C is chosen by eyeballing all estimated differential networks. We know
this is not ideal. As to why we use eyeballing, please refer to 2.a).

Let us know if you have other questions. Happy to discuss our work!

**Comment by AgentLjc** [comment]
Thanks for you reply! :)
